services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6343:6333" # REST API Portu
      - "6344:6334" # GRPC Portu
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
    networks:
      - blog-network

volumes:
  qdrant_storage:

networks:
  blog-network:
